### ISSUE TITLE
Will this work for Edimax EW-7811Un

### ISSUE THREAD

**Issue by SaimonL** [dz0ny/rt8192cu#16]
Hi I am having the same compile error for my "Edimax EW-7811Un" so I want to use your solution.
Will this driver in Git work for my "Edimax EW-7811Un" as well?
I am guessing not.

Thanks

**Comment by interfect** [comment]
It wouldn't hurt to try it. If the module doesn't think it can run the
device, it won't do anything.

Judging by <http://ubuntuforums.org/showthread.php?t=1744371>, it seems
like that device might have the appropriate chip inside it for this driver
to drive, so I would give it a shot.

**Comment by leewc** [comment]
It compiles nicely compared to the package in AUR, which has a deprecated string function causing the entire build to fail after 10 minutes of compiling on the  Pi.

Since the bundled raspberry pi kernel's driver isn't exactly functional. It's also mentioned in the wiki for Arch Linux that one should try the dkms version if the included drivers don't work, https://wiki.archlinux.org/index.php/Wireless_network_configuration#rtl8192cu

That however, has compile errors, a string method being deprecated in `os_dep/linux/rtw_android.c`, which this fork fixes nicely. I got it to install after cloning by doing a `make dkms` after `cd rt8192cu`, and then a `depmod -a` to refresh the drivers. 

Still couldn't connect to wifi though. Might give up the arch route of trying to accomplish what I want since I've been spending so much time on trying to get this to work.

**Comment by SaimonL** [comment]
Thanks. I just returned it and got a different card.
